/* Generated by Cython 0.24.1 */

#ifndef __PYX_HAVE__shaiya_itemmall
#define __PYX_HAVE__shaiya_itemmall


#ifndef __PYX_HAVE_API__shaiya_itemmall

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(void) setPoint(long, long);
__PYX_EXTERN_C DL_IMPORT(long) getpoint(long);

#endif /* !__PYX_HAVE_API__shaiya_itemmall */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initshaiya_itemmall(void);
#else
PyMODINIT_FUNC PyInit_shaiya_itemmall(void);
#endif

#endif /* !__PYX_HAVE__shaiya_itemmall */
