#ifndef __testMainFrame__
#define __testMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include

/** Implementing MainFrame */
class testMainFrame : public MainFrame
{
	public:
		/** Constructor */
		testMainFrame( wxWindow* parent );
	//// end generated class members
	
};

#endif // __testMainFrame__
